name: Playwright Tests - Auto Trigger

on:
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Install Allure CLI globally
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # Run Playwright tests and generate JUnit + Allure results
      - name: Run Playwright Tests
        run: |
          npx playwright test --grep PlaywrightWithGitHubActions \
          --reporter=junit,junit-results.xml,allure-playwright

      # Upload JUnit XML report
      - name: Upload JUnit Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: junit-results
          path: junit-results.xml
          retention-days: 30

      # Generate Allure report
      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      # Upload Allure HTML report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Upload Playwright HTML report
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
